### ISSUE TITLE
SSMS not scripting hidden columns in temporal tables

### ISSUE THREAD

**Issue by dbrownems** [microsoft/sqlmanagementobjects#65] opened 2021-08-06 22:37 UTC
Reported here: https://dba.stackexchange.com/questions/297682/we-are-using-mssql-2016-ssms-18-9-2-and-trying-to-script-out-a-system-versione

Run

```
CREATE TABLE Department
(
    DeptID INT NOT NULL PRIMARY KEY CLUSTERED
  , DeptName VARCHAR(50) NOT NULL
  , ManagerID INT NULL
  , ParentDeptID INT NULL
  , SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL 
  , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL 
  , PERIOD FOR SYSTEM_TIME (SysStartTime,SysEndTime)
)
WITH (SYSTEM_VERSIONING = ON);


```
then script the object back out and you'll get a script without `HIDDEN`

```


CREATE TABLE [dbo].[Department](
	[DeptID] [int] NOT NULL,
	[DeptName] [varchar](50) NOT NULL,
	[ManagerID] [int] NULL,
	[ParentDeptID] [int] NULL,
	[SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DeptID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [dbo].[MSSQL_TemporalHistoryFor_1205579333] )
)
go
```

**Comment by mikekilkenny** [comment] 2021-10-06 20:41
I'm using Microsoft.SqlServer.Management.Smo.Transfer with PowerShell and have been chasing this issue. I've created workarounds for other problems, but they were really caused by this actual bug.

**Comment by shueybubbles** [comment] 2021-10-06 21:06
a new SMO package is coming out today. Try 161.46521.71.

**Comment by shueybubbles** [comment] 2022-01-10 20:17
Closing this issue as the SMO part is done.

**Closed by shueybubbles** 2022-01-10 20:17 UTC
